apiVersion: apps/v1
kind: Deployment
metadata:
  name: project61-k8
spec:
  selector:
      matchLabels:
        app: project61-k8
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project61-k8
    spec:
      containers:
        - name: project61
          image: project61:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: project61
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: project61
  type: LoadBalancer
