apiVersion: apps/v1
kind: Deployment
metadata:
  name: project61-k8s
spec:
  selector:
      matchLabels:
        app: project61-k8s
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: project61-k8s
    spec:
      containers:
        - name: project61
          image: project61:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: project61-k8s
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: project61-k8s
  type: LoadBalancer
