pipeline {
    agent any

    tools {
        jdk "jdk-17"
        maven "maven3"
    }

    stages {
        stage('Checkout') {
            steps {
                //TODO: Change to forked repo
                git 'https://github.com/gitorko/project61'
            }
        }
        stage('Build') {
            steps {
                sh "./gradlew clean build"
            }
            post {
                // record the test results and archive the jar file.
                success {
                    junit 'build/test-results/test/TEST-*.xml'
                    archiveArtifacts 'build/libs/*.jar'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "./gradlew jibDockerBuild -Djib.to.tags=$BUILD_NUMBER"
            }
            post {
                // record the test results and archive the jar file.
                success {
                    junit 'build/test-results/test/TEST-*.xml'
                    archiveArtifacts 'build/libs/*.jar'
                }
            }
        }
        stage ('Push Docker Image') {
            steps {
                //TODO: docker hub push
                echo "Pushing docker image"
            }
        }
        stage('Deploy') {
            steps {
                 withKubeConfig([credentialsId: 'kubernetes-config']) {
                  sh '''
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project61-k8s
spec:
  selector:
      matchLabels:
        app: project61-k8s
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: project61-k8s
    spec:
      containers:
        - name: project61
          image: project61:$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: project61-k8s
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: project61-k8s
  type: LoadBalancer
                    '''
                }
            }
        }
    }
}
