apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app.kubernetes.io/name: counter
spec:
  containers:
    - name: counter
      image: busybox:stable
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - "for i in 5 4 3 2 1; do echo $i; done"
  restartPolicy: Never
