apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      ports:
        - containerPort: 80
    - name: html-updater
      image: busybox:stable
      command: ['sh', '-c', 'while true; do date > /html/index.html; sleep 1; done']
      volumeMounts:
        - mountPath: /html
          name: html
  volumes:
    - name: html
      emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000

