apiVersion: batch/v1
kind: Job
metadata:
  name: job-counter
  labels:
    app.kubernetes.io/name: job-counter
spec:
  template:
    spec:
      containers:
        - name: job-counter
          image: busybox:stable
          imagePullPolicy: IfNotPresent
          args:
            - /bin/sh
            - -c
            - "for i in 5 4 3 2 1; do echo $i; done"
      restartPolicy: Never
  backoffLimit: 4
