apiVersion: v1
kind: ConfigMap
metadata:
  name: app-setting
data:
  prop1: foo-bar
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:stable
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/config
          name: app-config-vol
      args:
        - /bin/sh
        - "-c"
        - "while true; do echo \"$(cat /etc/config/prop1)\"; sleep 30; done;"
  volumes:
    - name: app-config-vol
      configMap:
        name: app-setting
  restartPolicy: Never



