apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
    - name: html
      hostPath:
        path: /tmp/
        type: Directory
  containers:
    - name: nginx
      image: nginx:stable
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
    - name: html-updater
      image: busybox:stable
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date > /html/index.html; sleep 1; done
      volumeMounts:
        - mountPath: /html
          name: html
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000
