apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
  labels:
    app: nginx-v1
spec:
  selector:
    matchLabels:
      app: nginx-v1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
        - name: my-nginx
          image: my-nginx:1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-green
spec:
  type: NodePort
  selector:
    app: nginx-v1
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v2
  labels:
    app: nginx-v2
spec:
  selector:
    matchLabels:
      app: nginx-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-v2
    spec:
      containers:
        - name: my-nginx
          image: my-nginx:2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-blue
spec:
  type: NodePort
  selector:
    app: nginx-v2
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
